In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a.transpose())

[1 2 3 4]


In [43]:
import numpy as np
A=np.array([1,2,3,4])
A_t=A[:,np.newaxis]
print(A_t)
print(A_t.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [9]:
import numpy as np
A=np.array([[1,2,3,4]])
print(A)
print(A.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [10]:
u=np.array([[1,2,3]]).T
v=np.array([[5,6,7]]).T
print(u+v)

[[ 6]
 [ 8]
 [10]]


In [11]:
u=np.array([[1,2,3]]).T
print(u*3)

[[3]
 [6]
 [9]]


In [13]:
u=np.array([3,5,2])
v=np.array([1,4,7])
print(np.dot(u,v))

37


In [15]:
u=np.array([[3,5,2]])
v=np.array([[1,4,7]]).T
print(np.dot(u,v))

[[37]]


In [16]:
u=np.array([3,5])
v=np.array([1,4])
print(np.cross(u,v))

7


In [17]:
x=np.array([3,3,9])
y=np.array([1,4,12])
print(np.cross(x,y))

[  0 -27   9]


In [18]:
u=np.array([[1,2,3]]).T
v=np.array([[4,5,6]]).T
w=np.array([[7,8,9]]).T
print(3*u+4*v+5*w)

[[54]
 [66]
 [78]]


In [31]:
u=np.array([1,2,3])
u.reshape(3,1)

array([[1],
       [2],
       [3]])

In [33]:
A=np.array([[1,2],
           [3,4],
           [5,6],
           [7,8]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [35]:
A=np.array([[1,1,1,1],
           [2,2,2,2],
           [3,3,3,3],
           [4,4,4,4]])
print(A)
print(A.shape)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
(4, 4)


In [38]:
A=np.array([[1,2,3,4],
           [5,6,7,8]])
print(A)
print(A.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [39]:
S=np.array([[1,2,3,4],
           [2,5,6,7],
           [3,6,8,9],
           [4,7,9,0]])
print(S)
print(S.T)

[[1 2 3 4]
 [2 5 6 7]
 [3 6 8 9]
 [4 7 9 0]]
[[1 2 3 4]
 [2 5 6 7]
 [3 6 8 9]
 [4 7 9 0]]


In [40]:
A=np.zeros([5,3])
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
A=np.diag([1,2,3,4,5])
print(A)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [42]:
I=np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
p=np.array([[1,2,3,4]])
print(p)
print(p.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [46]:
A=np.array([[1,2],
            [3,4],
           [5,6]])
B=np.array([[10,20],
            [30,40],
           [50,60]])
print(A+B)

[[11 22]
 [33 44]
 [55 66]]


In [48]:
A=np.array([[1,4],
            [2,5],
           [3,6]])
print(A*2)

[[ 2  8]
 [ 4 10]
 [ 6 12]]


In [49]:
A=np.array([[1,2],
            [3,4],
           [5,6],
           [7,8]])
B=np.array([[2,3,4,5],
           [6,7,8,9]])
print(np.dot(A,B))

[[ 14  17  20  23]
 [ 30  37  44  51]
 [ 46  57  68  79]
 [ 62  77  92 107]]


In [50]:
A=np.array([[1,2],
            [3,4],
           [5,6]])
x=np.array([[4,5]]).T
print(np.dot(A,x))

[[14]
 [32]
 [50]]
