In [1]:
import numpy as np
from scipy import linalg

In [2]:
eng,mat,phy=np.loadtxt('score.csv',delimiter=',',usecols=(0,1,2),unpack=True)
print(eng.mean(),mat.mean(),phy.mean())
print(np.cov(eng),np.cov(mat),np.cov(phy))

79.1 80.6 80.1
54.98888888888888 188.04444444444442 181.87777777777777


In [3]:
eng,mat,phy=np.loadtxt('score.csv',delimiter=',',usecols=(0,1,2),unpack=True)
S=np.vstack((eng,mat,phy))
print(np.cov(S))

[[ 54.98888889  70.82222222  56.76666667]
 [ 70.82222222 188.04444444 175.15555556]
 [ 56.76666667 175.15555556 181.87777778]]


In [4]:
x=[2,2,4,8,4]
y=[2,6,6,8,8]
S=np.vstack((x,y))
print(np.cov(S))

[[6. 4.]
 [4. 6.]]


In [5]:
x=[2,2,4,8,4]
y=[2,6,6,8,8]
x=x-np.mean(x)
y=y-np.mean(y)
S=np.vstack((x,y))
print(S)
print(np.cov(S))

[[-2. -2.  0.  4.  0.]
 [-4.  0.  0.  2.  2.]]
[[6. 4.]
 [4. 6.]]


In [6]:
C=np.array([[6,4],
           [4,6]])
evalue,evector=linalg.eig(C)
print(evalue)
print(evector)

[10.+0.j  2.+0.j]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [7]:
x=[2,2,4,8,4]
y=[2,6,6,8,8]
x=x-np.mean(x)
y=y-np.mean(y)
A=np.vstack((x,y))
p_1=[0.707,0.707]
p_2=[-0.707,0.707]
P=np.vstack((p_1,p_2))
print(A)
print(np.dot(P,A))

[[-2. -2.  0.  4.  0.]
 [-4.  0.  0.  2.  2.]]
[[-4.242 -1.414  0.     4.242  1.414]
 [-1.414  1.414  0.    -1.414  1.414]]


In [8]:
A=[[0,0,0,2,2],
  [0,0,0,3,3],
  [0,0,0,1,1],
  [1,1,1,0,0],
  [2,2,2,0,0],
  [5,5,5,0,0],
  [1,1,1,0,0]]

U,sigma,VT=np.linalg.svd(A)
print(U)
print(sigma)
print(VT)

[[ 1.24153973e-16 -5.34522484e-01  8.37807144e-01 -6.21797365e-02
  -6.15166652e-02  6.14119433e-02  3.07059717e-02]
 [ 1.38448957e-32 -8.01783726e-01 -4.85697270e-01  3.48196811e-01
  -1.70447338e-17 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00 -2.67261242e-01 -2.18522479e-01 -9.20230960e-01
   1.23033330e-01 -1.22823887e-01 -6.14119433e-02]
 [-1.79605302e-01 -2.05774198e-17 -4.40327302e-02 -6.14209440e-02
  -9.19287207e-01 -3.05864745e-01 -1.52932373e-01]
 [-3.59210604e-01  2.46872204e-17 -8.80654604e-02 -1.22841888e-01
  -2.06818517e-01  8.95901251e-01 -5.20493747e-02]
 [-8.98026510e-01 -2.34936928e-17  5.28392762e-02  7.37051328e-02
   2.87266700e-01 -2.86777676e-01 -1.43388838e-01]
 [-1.79605302e-01  1.23436102e-17 -4.40327302e-02 -6.14209440e-02
  -1.03409259e-01 -5.20493747e-02  9.73975313e-01]]
[9.64365076e+00 5.29150262e+00 8.10743804e-16 8.49555901e-17
 7.85046229e-17]
[[-5.77350269e-01 -5.77350269e-01 -5.77350269e-01  0.00000000e+00
   0.00000000e+00]
 [-2.46566547e-16

In [9]:
U.shape

(7, 7)

In [10]:
A=[[0,0,0,2,2],
  [0,0,0,3,3],
  [0,0,0,1,1],
  [1,1,1,0,0],
  [2,2,2,0,0],
  [5,5,5,0,0],
  [1,1,1,0,0]]

U,sigma,VT=np.linalg.svd(A)
U_T_2x7=U.T[:2,:]
print(np.dot(U_T_2x7,A))
VT_2x5=VT.T[:2,:]
print(np.dot(VT_2x5,np.mat(A).T).T)

[[-5.56776436e+00 -5.56776436e+00 -5.56776436e+00  2.48307945e-16
   2.48307945e-16]
 [-7.63278329e-17 -7.63278329e-17 -7.63278329e-17 -3.74165739e+00
  -3.74165739e+00]]
[[-0.75502547 -0.87646191]
 [-1.13253821 -1.31469286]
 [-0.37751274 -0.43823095]
 [ 0.14663233 -1.26627719]
 [ 0.29326466 -2.53255437]
 [ 0.73316164 -6.33138594]
 [ 0.14663233 -1.26627719]]


In [11]:
U_T_2x7

array([[ 1.24153973e-16,  1.38448957e-32,  0.00000000e+00,
        -1.79605302e-01, -3.59210604e-01, -8.98026510e-01,
        -1.79605302e-01],
       [-5.34522484e-01, -8.01783726e-01, -2.67261242e-01,
        -2.05774198e-17,  2.46872204e-17, -2.34936928e-17,
         1.23436102e-17]])

In [12]:
A=[[0,0,0,2,2],
  [0,0,0,3,3],
  [0,0,0,1,1],
  [1,1,1,0,0],
  [2,2,2,0,0],
  [5,5,5,0,0],
  [1,1,1,0,0]]

U,sigma,VT=np.linalg.svd(A)
A_1=sigma[0]*np.dot(np.mat(U[:,0]).T,np.mat(VT[0,:]))
A_2=sigma[1]*np.dot(np.mat(U[:,1]).T,np.mat(VT[1,:]))
print(A_1+A_2)

[[ 6.13544436e-18 -1.03995782e-15 -1.03995782e-15  2.00000000e+00
   2.00000000e+00]
 [ 1.04609326e-15 -5.23046632e-16 -5.23046632e-16  3.00000000e+00
   3.00000000e+00]
 [ 3.48697754e-16 -1.74348877e-16 -1.74348877e-16  1.00000000e+00
   1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  7.69936548e-17
   7.69936548e-17]
 [ 2.00000000e+00  2.00000000e+00  2.00000000e+00 -9.23711205e-17
  -9.23711205e-17]
 [ 5.00000000e+00  5.00000000e+00  5.00000000e+00  8.79053493e-17
   8.79053493e-17]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00 -4.61855603e-17
  -4.61855603e-17]]
