In [1]:
import numpy as np
A_1=np.array([[1,1,0],
              [1,0,1]])
A_2=np.array([[1,2,-1],
              [2,4,-2]])
A_3=np.array([[1,0],
              [0,1],
             [0,-1]])
A_4=np.array([[1,2],
              [1,2],
             [-1,-2]])
A_5=np.array([[1,1,1],
              [1,1,2],
             [1,2,3]])
print(np.linalg.matrix_rank(A_1))
print(np.linalg.matrix_rank(A_2))
print(np.linalg.matrix_rank(A_3))
print(np.linalg.matrix_rank(A_4))
print(np.linalg.matrix_rank(A_5))

2
1
2
1
3


In [3]:
from scipy import linalg
A=np.array([[1,35,0],
           [0,2,3],
           [0,0,4]])
A_n=linalg.inv(A)
print(A_n)
print(np.dot(A,A_n))

[[  1.    -17.5    13.125]
 [  0.      0.5    -0.375]
 [  0.      0.      0.25 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Error
# B=np.array([[1,0,2],
#            [0,1,3],
#            [1,1,5]])
# B_n=linalg.inv(B)
# print(B_n)
# print(np.dot(B,B_n))

LinAlgError: singular matrix

In [8]:
A=np.array([[1,2,3],
           [1,-1,4],
           [2,3,-1]])
y=np.array([14,11,5])
x=linalg.solve(A,y)
print(x)

[1. 2. 3.]
