In [1]:
import numpy as np
from scipy import linalg

In [2]:
A=np.array([[2,1],
           [1,2]])
evalue,evector=linalg.eig(A)
print(evalue)
print(evector)

[3.+0.j 1.+0.j]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [3]:
A=np.array([[1,0,0],
           [0,2,0],
           [0,0,5]])
evalue,evector=linalg.eig(A)
print(evalue)
print(evector)

[1.+0.j 2.+0.j 5.+0.j]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
A=np.array([[1,6,0],
           [2,2,0],
           [0,0,5]])
evalue,evector=linalg.eig(A)
print(evalue)
print(evector)

[-2.+0.j  5.+0.j  5.+0.j]
[[-0.89442719 -0.83205029  0.        ]
 [ 0.4472136  -0.5547002   0.        ]
 [ 0.          0.          1.        ]]


In [5]:
A=np.array([[6,-2,1],
           [0,4,0],
           [0,0,6]])
evalue,evector=linalg.eig(A)
print(evalue)
print(evector)

[6.+0.j 4.+0.j 6.+0.j]
[[ 1.00000000e+00  7.07106781e-01 -1.00000000e+00]
 [ 0.00000000e+00  7.07106781e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.33226763e-15]]
